import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "GemFarm",
  description: "Generated by create next app",
  generator: "Next.js",
  manifest: "/manifest.json",
  keywords: ["nextjs", "next14", "pwa", "next-pwa"],
  authors: [
    {
      name: "Google",
      url: "https://www.google.com",
    },
  ],
  icons: [
    { rel: "apple-touch-icon", url: "icons/icon-128x128.png" },
    { rel: "icon", url: "icons/icon-120x120.png" },
  ],
};
