import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const cropLists = [
  {
    name: "Jalapenos",
    basePrice: 3.8,
    img: "",
    isPositive: true,
    systemType: "Dutch Bucket",
    category: "Fruiting Vegetables",
    variety: "Jalapeno",
  },
  {
    name: "Romaine Lettuce",
    basePrice: 1.37,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Romain.webp",
    isPositive: true,
    systemType: "NFT",
    category: "Leafy Greens",
    variety: "Lettuce",
  },
  {
    name: "Iceberg Lettuce",
    basePrice: 1.19,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Iceberg+Lettuce.webp",
    isPositive: true,
    systemType: "NFT",
    category: "Leafy Greens",
    variety: "Lettuce",
  },
  {
    name: "Butterhead Lettuce",
    basePrice: 1.29,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/butterhead.jpg",
    isPositive: true,
    systemType: "NFT",
    category: "Leafy Greens",
    variety: "Lettuce",
  },
  {
    name: "Loose Leaf Lettuce",
    basePrice: 1.57,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Loose+Leaf+Lettuce.webp",
    isPositive: true,
    systemType: "NFT",
    category: "Leafy Greens",
    variety: "Lettuce",
  },
  {
    name: "Arugula",
    basePrice: 16.18,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Arugula+(Rocket).webp",
    isPositive: false,
    systemType: "NFT",
    category: "Leafy Greens",
    variety: "Rocket",
  },
  {
    name: "Swiss Chard",
    basePrice: 22.5,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Swiss+Chard.webp",
    isPositive: true,
    systemType: "NFT",
    category: "Leafy Greens",
    variety: "Beta vulgaris",
  },
  {
    name: "Bok Choy",
    basePrice: 1.84,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Bok+Choy.webp",
    isPositive: false,
    systemType: "NFT",
    category: "Leafy Greens",
    variety: "Pak Choi",
  },
  {
    name: "Endive",
    basePrice: 2.89,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/EndiveCichorium+endivia.webp",
    isPositive: true,
    systemType: "NFT",
    category: "Leafy Greens",
    variety: "Cichorium endivia",
  },
  {
    name: "Watercress",
    basePrice: 4.78,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Watercress-spouts-640.webp",
    isPositive: false,
    systemType: "NFT",
    category: "Leafy Greens",
    variety: "Nasturtium officinale",
  },
  {
    name: "Basil",
    basePrice: 13.23,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Basil.jpg",
    isPositive: true,
    systemType: "NFT",
    category: "Herbs",
    variety: "Basil",
  },
  {
    name: "Cilantro",
    basePrice: 1.98,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Cilantro.webp",
    isPositive: true,
    systemType: "NFT",
    category: "Herbs",
    variety: "Coriander",
  },
  {
    name: "Parsley",
    basePrice: 2.95,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/parsley.webp",
    isPositive: true,
    systemType: "NFT",
    category: "Herbs",
    variety: "Parsley",
  },
  {
    name: "Mint",
    basePrice: 5.15,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/pepperminit.jpg",
    isPositive: true,
    systemType: "NFT",
    category: "Herbs",
    variety: "Peppermint",
  },
  {
    name: "Mint",
    basePrice: 13.5,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Spearmint.jpg",
    isPositive: true,
    systemType: "NFT",
    category: "Herbs",
    variety: "Spearmint",
  },
  {
    name: "Thyme",
    basePrice: 20.56,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Thyme-Bundle.jpg",
    isPositive: true,
    systemType: "NFT",
    category: "Herbs",
    variety: "Thyme",
  },
  {
    name: "Dill",
    basePrice: 21.67,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Dill.jpg",
    isPositive: true,
    systemType: "NFT",
    category: "Herbs",
    variety: "Dill",
  },
  {
    name: "Chives",
    basePrice: 25.56,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Chives.png",
    isPositive: true,
    systemType: "NFT",
    category: "Herbs",
    variety: "Chives",
  },
  {
    name: "Oregano",
    basePrice: 20.56,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Oregano.jpeg",
    isPositive: true,
    systemType: "NFT",
    category: "Herbs",
    variety: "Oregano",
  },
  {
    name: "Sage",
    basePrice: 22.22,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Sage.webp",
    isPositive: true,
    systemType: "NFT",
    category: "Herbs",
    variety: "Sage",
  },
  {
    name: "Rosemary",
    basePrice: 18.33,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Rosemary.webp",
    isPositive: true,
    systemType: "NFT",
    category: "Herbs",
    variety: "Rosemary",
  },
  {
    name: "Tarragon",
    basePrice: 26.67,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Tarragon.webp",
    isPositive: true,
    systemType: "NFT",
    category: "Herbs",
    variety: "Tarragon",
  },
  {
    name: "Lemon Balm",
    basePrice: 3.5,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/lemonbalm.jpeg",
    isPositive: true,
    systemType: "NFT",
    category: "Herbs",
    variety: "Lemon Balm",
  },
  {
    name: "Albion",
    basePrice: 7.3,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Albion+strawberries.webp",
    isPositive: true,
    systemType: "NFT",
    category: "Fruits",
    variety: "Strawberry",
  },
  {
    name: "Dwarf Cherry Tomatoes",
    basePrice: 6.62,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Dwarf-Cherry-Tomato-Rosie-F1-Hybrid.jpeg",
    isPositive: true,
    systemType: "NFT",
    category: "Small Fruiting Plants",
    variety: "Cherry Tomatoes",
  },
  {
    name: "Dwarf Peppers",
    basePrice: 2.07,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Mck_Vegetable_128571_Pepper_MiniBellMix.webp",
    isPositive: true,
    systemType: "NFT",
    category: "Small Fruiting Plants",
    variety: "Mini Bell Peppers",
  },
  {
    name: "Dwarf Peppers",
    basePrice: 2.04,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/jalapeno1-700x700.webp",
    isPositive: true,
    systemType: "NFT",
    category: "Small Fruiting Plants",
    variety: "Jalapeños",
  },
  {
    name: "Tomatoes",
    basePrice: 2.12,
    img: "TomatoImage",
    isPositive: true,
    systemType: "Dutch Bucket",
    category: "Fruiting Vegetables",
    variety: "Indeterminate",
  },
  {
    name: "Peppers",
    basePrice: 4.0,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Cayenne.webp",
    isPositive: true,
    systemType: "Dutch Bucket",
    category: "Fruiting Vegetables",
    variety: "Cayenne",
  },
  {
    name: "Eggplants",
    basePrice: 1.7,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/eggplants.webp",
    isPositive: true,
    systemType: "Dutch Bucket",
    category: "Fruiting Vegetables",
    variety: "Eggplants",
  },
  {
    name: "Cucumbers",
    basePrice: 5.57,
    img: "CucumberImage",
    isPositive: true,
    systemType: "Dutch Bucket",
    category: "Fruiting Vegetables",
    variety: "Cucumbers",
  },
  {
    name: "Zucchini",
    basePrice: 1.76,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/courgette-large.jpg",
    isPositive: true,
    systemType: "Dutch Bucket",
    category: "Fruiting Vegetables",
    variety: "Courgettes",
  },
  {
    name: "Squash",
    basePrice: 1.77,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Butternut+Squash.webp",
    isPositive: true,
    systemType: "Dutch Bucket",
    category: "Fruiting Vegetables",
    variety: "Butternut",
  },
  {
    name: "Squash",
    basePrice: 2.53,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Squash+(Pumpkin).webp",
    isPositive: true,
    systemType: "Dutch Bucket",
    category: "Fruiting Vegetables",
    variety: "Pumpkin",
  },
  {
    name: "Squash",
    basePrice: 1.43,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Acorn+Squash.webp",
    isPositive: true,
    systemType: "Dutch Bucket",
    category: "Fruiting Vegetables",
    variety: "Acorn",
  },
  {
    name: "Green Beans",
    basePrice: 2.17,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/farmscart-beans-polesuper.webp",
    isPositive: true,
    systemType: "Dutch Bucket",
    category: "Legumes & Climbing Plants",
    variety: "Pole Beans",
  },
  {
    name: "Green Beans",
    basePrice: 1.76,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/aeroponic-bush-beans-seedlings_900x.webp",
    isPositive: true,
    systemType: "Dutch Bucket",
    category: "Legumes & Climbing Plants",
    variety: "Bush Beans",
  },
  {
    name: "Peas",
    basePrice: 3.97,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Snow+Peas.webp",
    isPositive: true,
    systemType: "Dutch Bucket",
    category: "Legumes & Climbing Plants",
    variety: "Snow Peas",
  },
  {
    name: "Peas",
    basePrice: 5.37,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Sugar+Snap+Peas.jpg",
    isPositive: true,
    systemType: "Dutch Bucket",
    category: "Legumes & Climbing Plants",
    variety: "Sugar Snap Peas",
  },
  {
    name: "Cantaloupe",
    basePrice: 2.43,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Cantaloupe.jpg",
    isPositive: true,
    systemType: "Dutch Bucket",
    category: "Melons & Gourds",
    variety: "Cantaloupe",
  },
  {
    name: "Watermelon",
    basePrice: 1.51,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Dwarf.webp",
    isPositive: true,
    systemType: "Dutch Bucket",
    category: "Melons & Gourds",
    variety: "Compact",
  },

  {
    name: "Honeydew Melon",
    basePrice: 1.57,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/Honeydew+Melon.jpg",
    isPositive: true,
    systemType: "Dutch Bucket",
    category: "Melons & Gourds",
    variety: "Honeydew Melon",
  },
  {
    name: "Carrots",
    basePrice: 0.93,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/CarrotsParisian18085.png",
    isPositive: false,
    systemType: "Dutch Bucket",
    category: "Root Vegetables",
    variety: "Parisian",
  },
  {
    name: "Beets",
    basePrice: 2.43,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/beet.webp",
    isPositive: false,
    systemType: "Dutch Bucket",
    category: "Root Vegetables",
    variety: "Beets",
  },
  {
    name: "Radishes",
    basePrice: 3.53,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/radish_GyJvfNq_.jpg",
    isPositive: false,
    systemType: "Dutch Bucket",
    category: "Root Vegetables",
    variety: "Radishes",
  },
  {
    name: "Turnips",
    basePrice: 1.59,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/turnip.webp",
    isPositive: false,
    systemType: "Dutch Bucket",
    category: "Root Vegetables",
    variety: "Turnips",
  },
  {
    name: "Ginger",
    basePrice: 3.82,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/ginger-root.webp",
    isPositive: true,
    systemType: "Dutch Bucket",
    category: "Medicinal & Specialty Plants",
    variety: "Ginger",
  },
  {
    name: "Turmeric",
    basePrice: 20.0,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/turmeric_header.png",
    isPositive: true,
    systemType: "Dutch Bucket",
    category: "Medicinal & Specialty Plants",
    variety: "Turmeric",
  },
  {
    name: "Saffron",
    basePrice: 150.0,
    img: "https://dev-gemfarm.s3.us-east-1.amazonaws.com/images/benefits-of-saffron.webp",
    isPositive: true,
    systemType: "Dutch Bucket",
    category: "Medicinal & Specialty Plants",
    variety: "Saffron",
  },
]